// swarm-gen creates fresh graph-coloring instances with a known answer.
//
// Construction: split n vertices into k equal hidden color classes, add edges
// only between different classes, and plant a k-clique (one vertex per class).
// The hidden classes prove chi <= k, the clique proves chi >= k, so chi = k.
// Edges are "flat": every pair of classes gets the same number of edges, which
// removes the degree hints that make planted colorings easy to spot.
//
// Difficulty is set by the density p. Near the density where a random graph
// would naturally need about k colors, the hidden coloring is hard to find.
//
//	swarm-gen -n 250 -k 20 -p 0.42 -seed 7                 # write instances/generated/...
//	swarm-gen -n 250 -k 20 -p 0.42 -seed 7 -calibrate 2m   # time tabu search on it first
package main

import (
	"flag"
	"fmt"
	"log"
	"math/rand"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/jakeroggenbuck/swarm/internal/graph"
)

func main() {
	var (
		n         = flag.Int("n", 250, "vertices")
		k         = flag.Int("k", 20, "planted chromatic number")
		p         = flag.Float64("p", 0.42, "edge probability between different hidden classes")
		seed      = flag.Int64("seed", 1, "random seed (a new seed is a new, never-attempted instance)")
		name      = flag.String("name", "", "instance name (default planted<n>_<k>_s<seed>)")
		outDir    = flag.String("out", "instances/generated", "output directory")
		calibrate = flag.Duration("calibrate", 0, "instead of writing, time parallel tabu search on the instance for up to this long")
		workers   = flag.Int("workers", runtime.NumCPU(), "calibration: parallel tabu searches")
	)
	flag.Parse()
	if *name == "" {
		*name = fmt.Sprintf("planted%d_%d_s%d", *n, *k, *seed)
	}
	g, hidden, clique := generate(*name, *n, *k, *p, *seed)

	// Sanity: the construction must certify chi = k.
	if _, err := g.CheckColoring(hidden, *k); err != nil {
		log.Fatalf("planted coloring invalid: %v", err)
	}
	if err := g.CheckClique(clique); err != nil || len(clique) != *k {
		log.Fatalf("planted clique invalid: %v", err)
	}
	rng := rand.New(rand.NewSource(*seed))
	dsat := graph.NumColors(graph.DSatur(g, rng))
	natural, _ := graph.MaxClique(g, time.Now().Add(2*time.Second), rng)
	fmt.Printf("%s: n=%d m=%d density=%.3f  chi=%d (planted)  DSatur=%d  largest clique found=%d\n",
		*name, g.N, g.M, g.Density(), *k, dsat, len(natural))

	if *calibrate > 0 {
		runCalibration(g, *k, *workers, *calibrate)
		return
	}

	if err := os.MkdirAll(filepath.Join(*outDir, "solutions"), 0o755); err != nil {
		log.Fatal(err)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "c %s: generated by swarm-gen (never published)\n", *name)
	fmt.Fprintf(&b, "c construction: %d hidden classes, flat edges p=%.3f between classes, planted %d-clique\n", *k, *p, *k)
	fmt.Fprintf(&b, "c known: lower=%d upper=%d\n", *k, *k)
	body := g.DIMACS()
	b.WriteString(body[strings.Index(body, "p edge"):]) // drop the default comment line
	col := filepath.Join(*outDir, *name+".col")
	if err := os.WriteFile(col, []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	var s strings.Builder
	fmt.Fprintf(&s, "c hidden %d-coloring of %s (vertex color, 1-based vertices)\n", *k, *name)
	for v, c := range hidden {
		fmt.Fprintf(&s, "%d %d\n", v+1, c)
	}
	sol := filepath.Join(*outDir, "solutions", *name+".sol")
	if err := os.WriteFile(sol, []byte(s.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s and %s\n", col, sol)
}

// generate builds the instance. Vertices are shuffled so class membership is
// not visible in vertex ids.
func generate(name string, n, k int, p float64, seed int64) (*graph.Graph, []int, []int) {
	rng := rand.New(rand.NewSource(seed))
	perm := rng.Perm(n)
	hidden := make([]int, n)
	classes := make([][]int, k)
	for i, v := range perm {
		c := i % k
		hidden[v] = c
		classes[c] = append(classes[c], v)
	}
	var edges [][2]int
	// Flat: about p * |Ci| * |Cj| edges between each pair of classes.
	for i := 0; i < k; i++ {
		for j := i + 1; j < k; j++ {
			pairs := make([][2]int, 0, len(classes[i])*len(classes[j]))
			for _, a := range classes[i] {
				for _, b := range classes[j] {
					pairs = append(pairs, [2]int{a, b})
				}
			}
			rng.Shuffle(len(pairs), func(x, y int) { pairs[x], pairs[y] = pairs[y], pairs[x] })
			// Randomized rounding so p is a continuous knob: with 10 vertices per
			// class, plain rounding would only allow steps of 1/100.
			exact := p * float64(len(pairs))
			m := int(exact)
			if rng.Float64() < exact-float64(m) {
				m++
			}
			edges = append(edges, pairs[:m]...)
		}
	}
	clique := make([]int, k)
	for c := 0; c < k; c++ {
		clique[c] = classes[c][rng.Intn(len(classes[c]))]
	}
	for i := 0; i < k; i++ {
		for j := i + 1; j < k; j++ {
			edges = append(edges, [2]int{clique[i], clique[j]})
		}
	}
	sort.Ints(clique)
	return graph.New(name, n, edges), hidden, clique
}

// runCalibration races parallel tabu searches for a k-coloring, restarting
// each from a fresh DSatur start every 2M iterations, and reports the time
// to the first success.
func runCalibration(g *graph.Graph, k, workers int, limit time.Duration) {
	start := time.Now()
	deadline := start.Add(limit)
	var once sync.Once
	done := make(chan struct{})
	var wg sync.WaitGroup
	best := 1 << 30
	var mu sync.Mutex
	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func(w int) {
			defer wg.Done()
			rng := rand.New(rand.NewSource(int64(w)*7919 + time.Now().UnixNano()))
			stop := func() bool {
				select {
				case <-done:
					return true
				default:
					return time.Now().After(deadline)
				}
			}
			for !stop() {
				_, conf := graph.Tabucol(g, graph.DSatur(g, rng), graph.TabuOpts{K: k, MaxIters: 2_000_000, Rng: rng, Stop: stop})
				mu.Lock()
				if conf < best {
					best = conf
				}
				mu.Unlock()
				if conf == 0 {
					once.Do(func() {
						fmt.Printf("SOLVED: %d-coloring found by worker %d after %s\n", k, w, time.Since(start).Round(100*time.Millisecond))
						close(done)
					})
					return
				}
			}
		}(w)
	}
	wg.Wait()
	select {
	case <-done:
	default:
		fmt.Printf("NOT SOLVED in %s with %d workers (best: %d conflicting edges)\n", limit, workers, best)
	}
}
